### ISSUE TITLE
Remove Destroy Cloud Build Trigger and write Destroy process

### ISSUE THREAD

**Issue by ryanbianchi-bjss** [timant-dev/gcp-lz-bootstrap#25]
The Destroy Cloud Build Trigger needs to be removed. This is to lessen the danger of a Destroy job being inadvertently triggered and removing resources.

A Manual Destroy process needs to be written up to outline the steps an engineer would need to take if a Destroy is necessary.

**Comment by ryanbianchi-bjss** [comment]
Created remove_destroy branch

Removed Destroy trigger code

Tested successfully by running an apply on the current deployment in the timantrob.us org.

**Comment by ryanbianchi-bjss** [comment]
PR created https://github.com/timant-dev/gcp-lz-bootstrap/pull/26

**Comment by ryanbianchi-cgi** [comment]
PR Merged
