### ISSUE TITLE
Update error handling on local-exec step removing domain level projectCreator and billing.Creator roles

### ISSUE THREAD

**Issue by timantrobus** [timant-dev/gcp-lz-bootstrap#3]
- Currently the local-exec provisioner in the bootstrap Terraform `main.tf` fails if the `projectCreator` and/or `billing.Creator` roles are not present on the domain.
- Rework to make this step a no-op if these roles are already removed

**Comment by memnac** [comment]
There are two options - the first being the easiest with a one-line change while the second requires additional coding.

1) Override the default failure behaviour of local-exec provisioner to ignore error and continue apply. Do this by explicitly setting the "on-failure" meta-argument, like so :
`on_failure = continue` 
Link: https://www.terraform.io/docs/language/resources/provisioners/syntax.html#failure-behavior

2) Modify the local provisioners in main.tf to call a bash script which checks whether roles are present in domain. 
If they exist, script will remove them, else skip.

**main.tf** 
```
resource "null_resource" "remove-domain-billing-creator-role" {
  provisioner "local-exec" {
    command = "/bin/bash remove-default-roles.sh $ORG_ID $ORG_DOMAIN $ROLE"
    environment = {
      ORG_ID     = var.org_id
      ORG_DOMAIN = var.org_domain
      ROLE = "roles/billing.creator"
    }
  }
  depends_on = [
    google_organization_iam_member.tf-sa-org-iam-roles
  ]
}
```

```
resource "null_resource" "remove-domain-project-creator-role" {
  provisioner "local-exec" {
    command = "/bin/bash remove-default-roles.sh $ORG_ID $ORG_DOMAIN $ROLE"
    environment = {
      ORG_ID     = var.org_id
      ORG_DOMAIN = var.org_domain
      ROLE = "roles/resourcemanager.projectCreator"
    }
  }
  depends_on = [
    null_resource.remove-domain-billing-creator-role
  ]
}
```

**remove-default-roles.sh**

```
#!/bin/bash

set -o pipefail 

ORG_ID=$1
ORG_DOMAIN=$2
ROLE=$3

gcloud organizations get-iam-policy $ORG_ID --flatten=bindings --filter=bindings.role:$ROLE --format='value(bindings.members)' | grep domain:$ORG_DOMAIN
__ROLEEXISTS=$?

if [[ $__ROLEEXISTS == 0 ]]; then 
    # Role exists - remove!
    gcloud organizations remove-iam-policy-binding $ORG_ID --member=domain:$ORG_DOMAIN --role=$ROLE
else
    # Role doesn't exist - Continue / No-Ops
    echo "Entity $ROLE already exists - No further action needed!"
fi

```

**Comment by timantrobus** [comment]
Thanks for the comments on this issue @memnac 👍 

I opted for the approach of using a separate shell script that is invoked as the `command` argument of the local-exec provisioner.

The shell script makes use of a `gcloud` command to filter the IAM policy for the organisation to pick out any roles assigned to the domain and then to match them against the specific roles in question e.g. `roles/resourcemanager.projectCreator` and `roles/billing.creator`.

If the roles exist it removes them, otherwise the step is a no-op.

See `/scripts/remove-domain-role.sh` for details.

I'll close this issue as resolved now.
